# Generated by Django 4.2.11 on 2026-02-28 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('working_time', 'Durée du Travail'), ('rest', 'Temps de Repos'), ('night_work', 'Travail de Nuit'), ('overtime', 'Heures Supplémentaires'), ('vacation', 'Congés Payés'), ('pharmacy_specific', 'Spécifique Pharmacie')], max_length=30)),
                ('description', models.TextField()),
                ('legal_reference', models.CharField(max_length=200)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('threshold_unit', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compliance Rule',
                'verbose_name_plural': 'Compliance Rules',
                'db_table': 'hr_compliance_rules',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pharmacist_titular', 'Pharmacien Titulaire'), ('pharmacist_adjoint', 'Pharmacien Adjoint'), ('preparateur', 'Préparateur en Pharmacie'), ('clerk', 'Employé de Rayon'), ('intern', 'Stagiaire')], max_length=30)),
                ('contract_type', models.CharField(choices=[('cdi_full', 'CDI Temps Plein'), ('cdi_part', 'CDI Temps Partiel'), ('cdd', 'CDD'), ('alternance', 'Alternance')], max_length=20)),
                ('contract_hours', models.DecimalField(decimal_places=1, default=35.0, max_digits=4)),
                ('is_qualified_pharmacist', models.BooleanField(default=False)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('hire_date', models.DateField()),
                ('remaining_vacation_days', models.DecimalField(decimal_places=1, default=25.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'hr_employees',
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_duration', models.IntegerField(default=60, help_text='Break in minutes')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='draft', max_length=20)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hr_agent.employee')),
            ],
            options={
                'verbose_name': 'Work Shift',
                'verbose_name_plural': 'Work Shifts',
                'db_table': 'hr_shifts',
                'unique_together': {('employee', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], max_length=20)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='hr_agent.employee')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='hr_agent.compliancerule')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='hr_agent.workshift')),
            ],
            options={
                'verbose_name': 'Compliance Violation',
                'verbose_name_plural': 'Compliance Violations',
                'db_table': 'hr_compliance_violations',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'hr_chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('conge_paye', 'Congé Payé'), ('rtt', 'RTT'), ('maladie', 'Arrêt Maladie'), ('formation', 'Formation'), ('maternite', 'Congé Maternité/Paternité'), ('evenement_familial', 'Événement Familial'), ('autre', 'Autre')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En Attente'), ('approved', 'Approuvé'), ('refused', 'Refusé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('manager_comment', models.TextField(blank=True)),
                ('days_count', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_absences', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='hr_agent.employee')),
            ],
            options={
                'verbose_name': 'Absence Request',
                'verbose_name_plural': 'Absence Requests',
                'db_table': 'hr_absences',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'hr_audit_logs',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='hr_audit_lo_user_id_5137ed_idx'), models.Index(fields=['model_name', 'object_id'], name='hr_audit_lo_model_n_410b28_idx')],
            },
        ),
    ]
