// Mock data for development and offline mode
import { Employee, WorkShift, AbsenceRequest } from './api';

const today = new Date();
const weekStart = new Date(today);
weekStart.setDate(today.getDate() - today.getDay());

export const mockEmployees: Employee[] = [
  {
    id: 1,
    user: { id: 1, username: 'marie.dupont', first_name: 'Marie', last_name: 'Dupont', email: 'marie@pharmacy.local' },
    role: 'pharmacist_titular',
    role_display: 'Pharmacien Titulaire',
    contract_type: 'cdi_full',
    contract_type_display: 'CDI Temps Plein',
    contract_hours: 35,
    is_qualified_pharmacist: true,
    license_number: 'PHARM-001',
    phone: '06 12 34 56 78',
    hire_date: '2020-01-15',
    remaining_vacation_days: 18,
    created_at: '2020-01-15T00:00:00Z',
  },
  {
    id: 2,
    user: { id: 2, username: 'jean.martin', first_name: 'Jean', last_name: 'Martin', email: 'jean@pharmacy.local' },
    role: 'pharmacist_adjoint',
    role_display: 'Pharmacien Adjoint',
    contract_type: 'cdi_full',
    contract_type_display: 'CDI Temps Plein',
    contract_hours: 35,
    is_qualified_pharmacist: true,
    license_number: 'PHARM-002',
    phone: '06 23 45 67 89',
    hire_date: '2021-03-20',
    remaining_vacation_days: 22,
    created_at: '2021-03-20T00:00:00Z',
  },
  {
    id: 3,
    user: { id: 3, username: 'sophie.bernard', first_name: 'Sophie', last_name: 'Bernard', email: 'sophie@pharmacy.local' },
    role: 'preparateur',
    role_display: 'Préparateur en Pharmacie',
    contract_type: 'cdi_full',
    contract_type_display: 'CDI Temps Plein',
    contract_hours: 35,
    is_qualified_pharmacist: false,
    license_number: '',
    phone: '06 34 56 78 90',
    hire_date: '2022-06-01',
    remaining_vacation_days: 20,
    created_at: '2022-06-01T00:00:00Z',
  },
  {
    id: 4,
    user: { id: 4, username: 'pierre.lefevre', first_name: 'Pierre', last_name: 'Lefevre', email: 'pierre@pharmacy.local' },
    role: 'preparateur',
    role_display: 'Préparateur en Pharmacie',
    contract_type: 'cdi_part',
    contract_type_display: 'CDI Temps Partiel',
    contract_hours: 20,
    is_qualified_pharmacist: false,
    license_number: '',
    phone: '06 45 67 89 01',
    hire_date: '2023-01-10',
    remaining_vacation_days: 15,
    created_at: '2023-01-10T00:00:00Z',
  },
  {
    id: 5,
    user: { id: 5, username: 'luc.moreau', first_name: 'Luc', last_name: 'Moreau', email: 'luc@pharmacy.local' },
    role: 'clerk',
    role_display: 'Employé de Rayon',
    contract_type: 'cdi_full',
    contract_type_display: 'CDI Temps Plein',
    contract_hours: 35,
    is_qualified_pharmacist: false,
    license_number: '',
    phone: '06 56 78 90 12',
    hire_date: '2022-09-15',
    remaining_vacation_days: 21,
    created_at: '2022-09-15T00:00:00Z',
  },
];

export const mockShifts: WorkShift[] = [
  {
    id: 1,
    employee: 1,
    employee_name: 'Marie Dupont',
    date: new Date(weekStart.getTime() + 86400000).toISOString().split('T')[0],
    start_time: '08:30',
    end_time: '18:30',
    break_duration: 60,
    status: 'confirmed',
    status_display: 'Confirmé',
    is_night_shift: false,
    generated_by_ai: false,
    duration_hours: 9.5,
    notes: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    employee: 2,
    employee_name: 'Jean Martin',
    date: new Date(weekStart.getTime() + 86400000).toISOString().split('T')[0],
    start_time: '09:00',
    end_time: '17:30',
    break_duration: 60,
    status: 'confirmed',
    status_display: 'Confirmé',
    is_night_shift: false,
    generated_by_ai: false,
    duration_hours: 8.5,
    notes: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    employee: 3,
    employee_name: 'Sophie Bernard',
    date: new Date(weekStart.getTime() + 172800000).toISOString().split('T')[0],
    start_time: '10:00',
    end_time: '18:00',
    break_duration: 60,
    status: 'confirmed',
    status_display: 'Confirmé',
    is_night_shift: false,
    generated_by_ai: false,
    duration_hours: 8,
    notes: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    employee: 4,
    employee_name: 'Pierre Lefevre',
    date: new Date(weekStart.getTime() + 259200000).toISOString().split('T')[0],
    start_time: '14:00',
    end_time: '20:00',
    break_duration: 30,
    status: 'draft',
    status_display: 'Brouillon',
    is_night_shift: false,
    generated_by_ai: false,
    duration_hours: 5.5,
    notes: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    employee: 5,
    employee_name: 'Luc Moreau',
    date: new Date(weekStart.getTime() + 345600000).toISOString().split('T')[0],
    start_time: '08:30',
    end_time: '17:30',
    break_duration: 60,
    status: 'confirmed',
    status_display: 'Confirmé',
    is_night_shift: false,
    generated_by_ai: true,
    duration_hours: 9,
    notes: 'Generated by AI scheduler',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockAbsences: AbsenceRequest[] = [
  {
    id: 1,
    employee: 1,
    employee_name: 'Marie Dupont',
    type: 'conge_paye',
    type_display: 'Congé Payé',
    start_date: new Date(weekStart.getTime() + 1209600000).toISOString().split('T')[0],
    end_date: new Date(weekStart.getTime() + 1296000000).toISOString().split('T')[0],
    reason: 'Vacances familiales',
    status: 'pending',
    status_display: 'En Attente',
    manager_comment: '',
    approved_by: null,
    approved_by_name: null,
    days_count: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    employee: 3,
    employee_name: 'Sophie Bernard',
    type: 'maladie',
    type_display: 'Arrêt Maladie',
    start_date: today.toISOString().split('T')[0],
    end_date: new Date(today.getTime() + 86400000).toISOString().split('T')[0],
    reason: 'Grippe',
    status: 'pending',
    status_display: 'En Attente',
    manager_comment: '',
    approved_by: null,
    approved_by_name: null,
    days_count: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockCompliance = {
  is_compliant: false,
  violations: [
    {
      rule: 'MAX_WEEKLY_HOURS',
      severity: 'warning',
      message: 'Heures supplémentaires importantes: 42h',
      legal_ref: 'Art. L3121-27',
      current_value: 42,
      threshold: 35,
    },
  ],
  warnings: [
    {
      rule: 'NIGHT_SHIFT_MAX',
      severity: 'info',
      message: 'Shift de nuit: 8h (limite: 8h)',
      legal_ref: 'Art. L3122-7',
      current_value: 8,
      threshold: 8,
    },
  ],
  compliance_score: 85,
  total_hours: 42,
};
